### ISSUE TITLE
Create libzfs bindings

### ISSUE THREAD

**Issue by jgrund** [intel-hpdd/rust-libzfs#6]
Create libzfs bindings so we can programmatically call into libzfs and fetch info about imported pools, datasets and vdevs.

This issue has multiple parts:

  - [x] Create low level set of bindings around libzfs using bindgen (#1).
  - [x] Create higher level rusty bindings around the generated `libzfs-sys` (#3).
  - [x] Update the existing `nvpair` rust crate to allow for fetching of nvpair / nvlist values.
  - [x] Wrap the `libzfs` lib again with `neon` so we can call into libzfs via node. (#11)
  - [x] Create bindings from `libzfs-node` to F# via Fable.
  - [x] Create build infrastructure for test / releasing in travis.

**Comment by jgrund** [comment]
[IML_4_1_0 Scope Schedule Final.pdf](https://github.com/intel-hpdd/rust-libzfs/files/1553146/IML_4_1_0.Scope.Schedule.Final.pdf)
